name: Deploy to firebase

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Check node version
        run: node -v
      - run: npm ci
      - name: Build Project
        run: CI=false npm run build
      - name: GitHub Action for Firebase
        run: npm install -g firebase-tools@10.9.2
      - run: firebase init
      - run: firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}